import { faker } from '@faker-js/faker';

export class ProductBuilder {
  constructor() {
    // Product data generated by Faker for realism
    this.productData = {
      nome: faker.commerce.productName(),
      preco: parseInt(faker.commerce.price({ min: 10, max: 1000, dec: 0, symbol: '' })),
      descricao: faker.commerce.productDescription(),
      quantidade: faker.number.int({ min: 1, max: 100 })
    };
  }

  // 🏁 Método final que constrói o objeto
  build() {
    return { ...this.productData }; // Retorna uma cópia dos dados
  }

  // 🚀 Método estático para iniciar a construção
  static new() {
    return new ProductBuilder();
  }
}
