import { faker } from '@faker-js/faker';

export class UserBuilder {
  constructor() {
    // Data generated by Faker for realism
    this.userNew = {
      nome: faker.person.fullName(),
      email: faker.internet.email({ provider: 'teste.com' }),
      password: faker.internet.password(),
      administrador: 'true'  // User is an administrator by default
    };
  }

  // Method to set the email
  withEmail(email) {
    this.userNew.email = email;
    return this;
  }

  // Method to create the final object
  build() {
    return { ...this.userNew }; // Returns a copy of the data
  }

  // Method to start the building process
  static new() {
    return new UserBuilder();
  }
}
